#!/bin/bash

ITER=500

if [ "$#" -eq 0 ]; then
	./gen 100 100
fi

if [ ! -d states ]; then
    mkdir states
fi
if [ ! -d images ]; then
    mkdir images
fi

i=0
while [ $i -le $ITER ];
do	
	if [ "$#" -eq 1 ]; then
		./life $i $1
		mv life.dat states/life$i.dat
	elif [ "$#" -eq 0 ]; then
		./life $i
		mv life.dat states/life$i.dat
	fi
	let i=i+1
done

gnuplot -e "ITER=$ITER" draw
