#!/bin/bash

ITER=500

if [ ! -d states ]; then
    mkdir states
fi
if [ ! -d images ]; then
    mkdir images
fi

i=0
while [ $i -le $ITER ];
do
	./life $i
	mv life.dat states/life$i.dat
	let i=i+1
done

gnuplot -e "ITER=$ITER" draw
